import type { VercelRequest, VercelResponse } from '@vercel/node';
import crypto from 'node:crypto';
import { callProjectAdminRpc, callProjectAdminTableRpc } from '../_lib/projectAdminDb.js';

// ─── Daily notification safety-net sweep (Vercel Cron) ────────────────────
// PREVIOUS root cause of hours-late push delivery: this daily sweep used to
// be the ONLY thing that ever turned an unsent `notifications` row into an
// actual FCM push -- a notification created just after this ran waited up
// to ~24h for the next tick. Fixed not by running this MORE OFTEN (Vercel's
// Hobby plan caps cron invocation frequency to once/day regardless of the
// schedule string configured, so an hourly entry here would silently still
// only fire daily -- do not "optimize" this back to hourly) but by adding a
// request-triggered delivery path that fires immediately at the moment each
// transactional notification is created: api/webhook/paystack.ts (for the
// ticket-transfer fee flow -- see notifyTransferFeeOutcome there) and the
// client, via triggerPushDelivery() (src/lib/pushNotifications.ts) right
// after initiate/decline-transfer and the admin service-provider decision,
// both hitting api/push/send.ts's `deliverForUserId` mode. See
// api/_lib/pushDelivery.ts for the shared delivery logic those share.
//
// This daily run is now purely the SAFETY NET for whatever that on-demand
// path misses (app closed before the client-side call fires, a delivery
// call that itself failed, etc.) and the home for the 24h/1h event-reminder
// sweep below, which has no "moment of creation" to hook a trigger onto in
// the first place -- both of those are fine to run once/day. It intentionally
// still delivers ALL unsent notifications for ALL users (not just the ones
// the reminder sweep just created), which is what makes it a real safety
// net rather than only covering reminders.
// Combines what were originally two separate cron endpoints
// (event-reminders.ts + send-pending-pushes.ts) into one file, in that
// order — the Hobby-plan 12-serverless-function cap forced the merge, but
// running them sequentially in one invocation is actually the better
// design anyway: a 24h/1h reminder generated by the sweep gets delivered
// in the SAME run instead of waiting for a separate cron's next daily tick.
//
// 1) run_event_reminder_sweep() — populates 24h/1h-out reminder
//    notifications (push_data included) for ticket holders. All the
//    "which tickets, which window, have I already reminded this one" logic
//    lives in that RPC (migrations/20260806020300_event-reminder-sweep.sql)
//    since it's a set-based query best done in Postgres.
// 2) The FCM v1 delivery worker — reads every unsent notification row
//    across ALL users (not just ones the reminder sweep just created —
//    ticket-purchase/message/sale/event-update notifications from earlier
//    in the day are still sitting unsent too) and actually delivers them,
//    reusing the same JWT-signing approach as api/push/send.ts (kept
//    duplicated rather than shared — that endpoint authenticates with a
//    caller's super-admin session, this one with the project_admin DB
//    connection + a CRON_SECRET; different enough auth shape that sharing
//    a handler would be more confusing than one extra file was).
//
// No user session exists for a scheduled job, so this reads/writes the
// database via a direct project_admin Postgres connection (the same
// pattern api/webhook/paystack.ts and api/wallet/reconcile-payouts.ts
// already use — see api/_lib/projectAdminDb.ts for why a plain API key/
// JWT isn't an option on this project) against RPCs locked to
// `project_admin`.

function b64url(input: Buffer | string): string {
  const buf = typeof input === 'string' ? Buffer.from(input, 'utf8') : input;
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

async function getAccessToken(sa: { client_email: string; private_key: string }): Promise<string> {
  const now = Math.floor(Date.now() / 1000);
  const header = b64url(JSON.stringify({ alg: 'RS256', typ: 'JWT' }));
  const claim = b64url(JSON.stringify({
    iss: sa.client_email,
    scope: 'https://www.googleapis.com/auth/firebase.messaging',
    aud: 'https://oauth2.googleapis.com/token',
    iat: now,
    exp: now + 3600,
  }));
  const signer = crypto.createSign('RSA-SHA256');
  signer.update(`${header}.${claim}`);
  const signature = b64url(signer.sign(sa.private_key));
  const assertion = `${header}.${claim}.${signature}`;

  const res = await fetch('https://oauth2.googleapis.com/token', {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'urn:ietf:params:oauth:grant-type:jwt-bearer',
      assertion,
    }),
  });
  if (!res.ok) throw new Error(`Google token exchange failed: ${res.status}`);
  const data = await res.json();
  return data.access_token as string;
}

interface PendingRow {
  notification_id: string;
  user_id: string;
  title: string;
  body: string;
  push_data: Record<string, string> | null;
  token: string | null;
  platform: string | null;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== 'GET' && req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Vercel injects this header automatically for cron-triggered invocations
  // when CRON_SECRET is set — see https://vercel.com/docs/cron-jobs/manage-cron-jobs.
  // Without this check anyone who found the URL could trigger unlimited FCM
  // sends against every user's device.
  const cronSecret = process.env.CRON_SECRET;
  if (!cronSecret || req.headers.authorization !== `Bearer ${cronSecret}`) {
    return res.status(401).json({ error: 'Not authorized' });
  }

  // ── 0) Event lifecycle archival sweep ──────────────────────────────────
  // Soft-archives events whose effective end passed >7 days ago (see
  // migrations/0051_event_lifecycle_single_source_of_truth.sql). Runs first
  // and independently of the reminder/push steps below so a missing FCM
  // config never blocks it. Idempotent — safe to re-run every day.
  let archiveResult: any = null;
  try {
    archiveResult = await callProjectAdminRpc<number>('archive_ended_events', []);
  } catch (err: any) {
    archiveResult = { error: `archive sweep failed: ${err?.message || err}` };
  }

  // ── 1) Reminder sweep ──────────────────────────────────────────────────
  let reminderResult: any = null;
  try {
    const sweepRows = await callProjectAdminTableRpc<any>('run_event_reminder_sweep', []);
    reminderResult = sweepRows[0] ?? null;
  } catch (err: any) {
    reminderResult = { error: `sweep failed: ${err?.message || err}` };
  }

  // ── 2) Push delivery ────────────────────────────────────────────────────
  const saJson = process.env.FCM_SERVICE_ACCOUNT_JSON;
  if (!saJson) {
    return res.status(200).json({ archived: archiveResult, reminders: reminderResult, push: { error: 'FCM_SERVICE_ACCOUNT_JSON missing' } });
  }

  let sa: { project_id: string; client_email: string; private_key: string };
  try {
    sa = JSON.parse(saJson);
  } catch {
    return res.status(200).json({ archived: archiveResult, reminders: reminderResult, push: { error: 'FCM_SERVICE_ACCOUNT_JSON is not valid JSON' } });
  }

  let rows: PendingRow[];
  try {
    rows = await callProjectAdminTableRpc<PendingRow>('get_pending_push_notifications', [200]);
  } catch (err: any) {
    return res.status(200).json({ archived: archiveResult, reminders: reminderResult, push: { error: 'Failed to read pending notifications', detail: String(err?.message || err) } });
  }
  if (!rows.length) {
    return res.status(200).json({ archived: archiveResult, reminders: reminderResult, push: { sent: 0, pruned: 0, marked: 0 } });
  }

  let accessToken: string;
  try {
    accessToken = await getAccessToken(sa);
  } catch (err: any) {
    return res.status(200).json({ archived: archiveResult, reminders: reminderResult, push: { error: 'FCM auth failed', detail: String(err?.message || err) } });
  }

  const endpoint = `https://fcm.googleapis.com/v1/projects/${sa.project_id}/messages:send`;
  let sent = 0;
  const pruned = new Set<string>();
  // A notification with no device token (user never registered one) has
  // nothing to send but must still be marked, or it gets re-selected by
  // get_pending_push_notifications on every future run forever.
  const toMark = new Set<string>();

  await Promise.all(rows.map(async (row) => {
    if (!row.token) { toMark.add(row.notification_id); return; }

    // FCM's `data` payload must be flat string->string — App.tsx's
    // pushActionRef reads eventId/userId/screen directly off this object.
    const data: Record<string, string> = {};
    if (row.push_data) {
      for (const [k, v] of Object.entries(row.push_data)) data[k] = String(v);
    }

    const resp = await fetch(endpoint, {
      method: 'POST',
      headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        message: {
          token: row.token,
          notification: { title: row.title, body: row.body || '' },
          data,
          android: { priority: 'high', notification: { sound: 'default' } },
        },
      }),
    });

    if (resp.ok) { sent++; toMark.add(row.notification_id); return; }

    // Parsed once, for every non-OK status — previously only 404/400 ever
    // inspected the body, so nothing about a 401/403/5xx failure was ever
    // visible anywhere. Never includes the token or the request itself.
    const errJson = await resp.json().catch(() => null);
    const code = errJson?.error?.details?.[0]?.errorCode || errJson?.error?.status;

    if (resp.status === 404 || resp.status === 400) {
      if (code === 'UNREGISTERED' || code === 'INVALID_ARGUMENT') {
        // Permanently dead token — nothing will ever make this send
        // succeed, so mark it sent (there's no point retrying) and prune
        // the token so future notifications skip it entirely.
        pruned.add(row.token);
        toMark.add(row.notification_id);
        await callProjectAdminRpc('prune_push_token', [row.token]).catch(() => {});
        return;
      }
    }
    // Any other failure (rate limit, transient 5xx) — deliberately NOT
    // added to toMark, so push_sent stays false and the next sweep retries
    // it. The notification itself still shows in the in-app bell either way.
    // TEMP DIAGNOSTIC — remove once real iOS delivery is confirmed working.
    // Logs only the HTTP status and FCM's own error status/message (with the
    // device token stripped out of the message on the off chance FCM ever
    // echoes it back) — never the token, the Authorization header, the FCM
    // access token, or any other credential.
    const fcmMessage = typeof errJson?.error?.message === 'string'
      ? errJson.error.message.split(row.token).join('[token redacted]')
      : null;
    console.error('[cron:push] FCM send failed', {
      httpStatus: resp.status,
      fcmStatus: errJson?.error?.status ?? null,
      fcmErrorCode: code ?? null,
      fcmMessage,
    });
  }));

  if (toMark.size > 0) {
    await callProjectAdminRpc('mark_notifications_pushed', [Array.from(toMark)]).catch(() => {});
  }

  return res.status(200).json({
    archived: archiveResult,
    reminders: reminderResult,
    push: { sent, pruned: pruned.size, marked: toMark.size, total: rows.length },
  });
}
