export const CATEGORIES = [
  { id: 'Music', label: 'Music', icon: '🎵' },
  { id: 'Technology', label: 'Tech', icon: '💻' },
  { id: 'Food & Drinks', label: 'Food', icon: '🍔' },
  { id: 'Comedy Shows', label: 'Comedy', icon: '🎤' },
  { id: 'Arts & Culture', label: 'Arts', icon: '🎨' },
  { id: 'Sports & Wellness', label: 'Sports', icon: '⚽' },
  { id: 'Conferences', label: 'Business', icon: '💼' },
  { id: 'Family Events', label: 'Family', icon: '👨‍👩‍👧‍👦' },
  { id: 'Nightlife', label: 'Nightlife', icon: '🌃' },
  { id: 'Fashion', label: 'Fashion', icon: '👗' },
  { id: 'Health & Wellness', label: 'Wellness', icon: '🧘' },
  { id: 'Education', label: 'Education', icon: '📚' },
  { id: 'Weddings', label: 'Weddings', icon: '💍' },
  { id: 'Gaming', label: 'Gaming', icon: '🎮' },
  { id: 'Business & Finance', label: 'Finance', icon: '💰' },
  { id: 'Religious & Spiritual', label: 'Religious', icon: '🙏' },
  { id: 'Charity & Fundraising', label: 'Charity', icon: '❤️' },
  { id: 'Film & Media', label: 'Film', icon: '🎬' },
  { id: 'Politics', label: 'Politics', icon: '🏛️' },
  { id: 'Travel & Adventure', label: 'Travel', icon: '✈️' },
  { id: 'Kids & Family', label: 'Kids', icon: '🧸' },
  { id: 'Art Exhibition', label: 'Exhibition', icon: '🖼️' },
  { id: 'Open Mic', label: 'Open Mic', icon: '🎙️' },
  { id: 'Workshop', label: 'Workshop', icon: '🛠️' },
];
