import { Event, UserProfile, Notification } from './types';

export const EVENTS: Event[] = [
  {
    id: '1',
    title: 'Afrobeats Fest Lagos 2026',
    category: 'Music',
    categoryIcon: '🎵',
    date: 'Sat, Jul 19, 2026',
    time: '7:00 PM',
    endTime: '2:00 AM',
    venue: 'Eko Hotel & Suites',
    area: 'Victoria Island',
    city: 'Lagos',
    state: 'Lagos State',
    price: 5000,
    image: 'https://images.unsplash.com/photo-1594122107730-a03f3ccaf301?w=800&fit=crop&crop=center',
    description: 'The biggest Afrobeats festival in West Africa returns! Experience a night of incredible music featuring top Nigerian artists and international headliners. Dance the night away with live performances, DJ sets, and amazing vibes across multiple stages.',
    organizer: 'EventsLagos Pro',
    organizerVerified: true,
    isFeatured: true,
    isTrending: true,
    attendees: 3820,
    capacity: 5000,
    rating: 4.8,
    reviewCount: 284,
    lineup: ['Burna Boy', 'Wizkid', 'Davido', 'Tiwa Savage', 'Asake'],
    tags: ['Live Music', 'Outdoor', 'Afrobeats', 'Night Event'],
    contactPhone: '+234 801 234 5678',
    ticketTypes: [
      { id: 't1', name: 'Regular', price: 5000, description: 'General admission', available: 1200 },
      { id: 't2', name: 'VIP', price: 15000, description: 'VIP lounge + 2 drinks + fast track', available: 380 },
      { id: 't3', name: 'VVIP Table', price: 50000, description: 'Private table for 4 + bottle service', available: 42 },
    ],
  },
  {
    id: '2',
    title: 'Lagos Food & Drink Festival',
    category: 'Food & Drinks',
    categoryIcon: '🍽️',
    date: 'Sun, Jul 26, 2026',
    time: '12:00 PM',
    endTime: '9:00 PM',
    venue: 'Lekki Conservation Centre',
    area: 'Lekki',
    city: 'Lagos',
    state: 'Lagos State',
    price: 3000,
    image: 'https://images.unsplash.com/photo-1765584829902-51939816637c?w=800&fit=crop&crop=center',
    description: 'A celebration of Nigerian cuisine and international flavors. Meet top chefs, taste signature dishes, enjoy live cooking demonstrations, and discover beverages from local craft breweries and restaurants.',
    organizer: 'FoodieNaija',
    organizerVerified: true,
    isFeatured: true,
    isTrending: true,
    attendees: 1340,
    capacity: 2000,
    rating: 4.6,
    reviewCount: 192,
    tags: ['Food', 'Outdoor', 'Family-friendly', 'Live Cooking'],
    ticketTypes: [
      { id: 't1', name: 'Standard', price: 3000, description: 'Entry + 5 tasting tokens', available: 660 },
      { id: 't2', name: 'Premium', price: 8000, description: 'Fast-track entry + unlimited tastings', available: 140 },
    ],
  },
  {
    id: '3',
    title: 'NG Tech Summit 2026',
    category: 'Technology',
    categoryIcon: '💻',
    date: 'Thu, Aug 9, 2026',
    time: '9:00 AM',
    endTime: '6:00 PM',
    venue: 'Transcorp Hilton',
    area: 'Maitama',
    city: 'Abuja',
    state: 'FCT',
    price: 10000,
    image: 'https://images.unsplash.com/photo-1754373695753-1069438691f8?w=800&fit=crop&crop=center',
    description: "Nigeria's premier technology conference bringing together innovators, entrepreneurs, and investors. Features keynotes, panels, workshops, and networking opportunities with tech leaders across Africa.",
    organizer: 'TechAbuja Hub',
    organizerVerified: true,
    isFeatured: true,
    isTrending: false,
    attendees: 1870,
    capacity: 3000,
    rating: 4.9,
    reviewCount: 341,
    lineup: ['Shola Akinlade (Paystack)', 'Mitchell Elegbe (Interswitch)', 'Sim Shagaya'],
    tags: ['Tech', 'Networking', 'Innovation', 'Startup'],
    ticketTypes: [
      { id: 't1', name: 'Standard Pass', price: 10000, description: 'Full conference access', available: 930 },
      { id: 't2', name: 'Speaker Track', price: 25000, description: 'All sessions + speaker lunch', available: 160 },
      { id: 't3', name: 'Workshop Bundle', price: 45000, description: 'All access + 3 workshops', available: 40 },
    ],
  },
  {
    id: '4',
    title: 'Comedy Night Lagos',
    category: 'Comedy Shows',
    categoryIcon: '😂',
    date: 'Sat, Aug 15, 2026',
    time: '7:30 PM',
    endTime: '11:00 PM',
    venue: 'Terra Kulture',
    area: 'Victoria Island',
    city: 'Lagos',
    state: 'Lagos State',
    price: 6000,
    image: 'https://images.unsplash.com/photo-1589707181684-24a34853641d?w=800&fit=crop&crop=center',
    description: "Nigeria's funniest comedians take the stage for an unforgettable night of laughter. Featuring headliners from Lagos and special guests from across Nigeria.",
    organizer: 'Laff All Day',
    organizerVerified: false,
    isFeatured: false,
    isTrending: true,
    attendees: 560,
    capacity: 800,
    rating: 4.7,
    reviewCount: 118,
    lineup: ['Basketmouth', 'AY Makun', 'Bovi', 'Falz'],
    tags: ['Comedy', 'Nightlife', 'Indoor', 'Adult'],
    ticketTypes: [
      { id: 't1', name: 'Regular', price: 6000, description: 'General admission', available: 240 },
      { id: 't2', name: 'Premium Seating', price: 12000, description: 'Front section + 2 drinks', available: 80 },
    ],
  },
  {
    id: '5',
    title: 'Port Harcourt Jazz Night',
    category: 'Music',
    categoryIcon: '🎵',
    date: 'Fri, Aug 2, 2026',
    time: '8:00 PM',
    endTime: '11:30 PM',
    venue: 'Hotel Presidential',
    area: 'GRA Phase 2',
    city: 'Port Harcourt',
    state: 'Rivers State',
    price: 7000,
    image: 'https://images.unsplash.com/photo-1761370980973-a3e04e9f242b?w=800&fit=crop&crop=center',
    description: 'An elegant evening of live jazz music featuring renowned Nigerian jazz artists. Enjoy an intimate atmosphere with exquisite dining and world-class musical performances.',
    organizer: 'PH Cultural Events',
    organizerVerified: false,
    isFeatured: false,
    isTrending: true,
    attendees: 310,
    capacity: 500,
    rating: 4.5,
    reviewCount: 76,
    tags: ['Jazz', 'Intimate', 'Fine Dining', 'Indoor'],
    ticketTypes: [
      { id: 't1', name: 'Standing', price: 7000, description: 'General admission', available: 140 },
      { id: 't2', name: 'Table for 2', price: 14000, description: 'Dinner for 2 + live jazz', available: 25 },
    ],
  },
  {
    id: '6',
    title: 'Abuja BBQ & Grill Fest',
    category: 'Food & Drinks',
    categoryIcon: '🍽️',
    date: 'Sun, Aug 9, 2026',
    time: '1:00 PM',
    endTime: '8:00 PM',
    venue: 'Abuja Recreation Club',
    area: 'CBD',
    city: 'Abuja',
    state: 'FCT',
    price: 4000,
    image: 'https://images.unsplash.com/photo-1765584829997-12ab011bb5b3?w=800&fit=crop&crop=center',
    description: 'The biggest outdoor BBQ event in Abuja. Enjoy suya, peppered chicken, ribs, and more from the best grillmasters in the city. Live music, cold drinks, and great company!',
    organizer: 'AbujaEats',
    organizerVerified: false,
    isFeatured: false,
    isTrending: false,
    attendees: 870,
    capacity: 1200,
    rating: 4.4,
    reviewCount: 98,
    tags: ['Outdoor', 'BBQ', 'Family', 'Music'],
    ticketTypes: [
      { id: 't1', name: 'Entry', price: 4000, description: 'Entry + welcome drink + 3 tokens', available: 330 },
    ],
  },
  {
    id: '7',
    title: 'Digital Africa Conference',
    category: 'Technology',
    categoryIcon: '💻',
    date: 'Wed, Aug 20, 2026',
    time: '9:00 AM',
    endTime: '5:00 PM',
    venue: 'Landmark Centre',
    area: 'Oniru',
    city: 'Lagos',
    state: 'Lagos State',
    price: 15000,
    image: 'https://images.unsplash.com/photo-1720700126947-a6ba1ebba73d?w=800&fit=crop&crop=center',
    description: "Africa's digital transformation conference. Explore AI, fintech, healthtech, and agritech innovations driving the continent forward.",
    organizer: 'Digital Africa Foundation',
    organizerVerified: true,
    isFeatured: false,
    isTrending: true,
    attendees: 1920,
    capacity: 2500,
    rating: 4.8,
    reviewCount: 267,
    tags: ['AI', 'Fintech', 'Networking', 'Innovation'],
    ticketTypes: [
      { id: 't1', name: 'Regular', price: 15000, description: 'Full conference access', available: 580 },
      { id: 't2', name: 'VIP', price: 35000, description: 'All access + networking dinner', available: 110 },
    ],
  },
  {
    id: '8',
    title: 'Lagos Street Food Fiesta',
    category: 'Food & Drinks',
    categoryIcon: '🍽️',
    date: 'Sat, Aug 29, 2026',
    time: '2:00 PM',
    endTime: '10:00 PM',
    venue: 'National Theatre Grounds',
    area: 'Iganmu',
    city: 'Lagos',
    state: 'Lagos State',
    price: 2000,
    image: 'https://images.unsplash.com/photo-1673280401347-309363111070?w=800&fit=crop&crop=center',
    description: "Celebrate the rich street food culture of Lagos! Taste boli, suya, akara, jollof rice, and more from Lagos's best street vendors.",
    organizer: 'Naija Street Events',
    organizerVerified: false,
    isFeatured: false,
    isTrending: false,
    attendees: 2140,
    capacity: 3000,
    rating: 4.3,
    reviewCount: 145,
    tags: ['Street Food', 'Family', 'Outdoor', 'Music'],
    ticketTypes: [
      { id: 't1', name: 'Entry', price: 2000, description: 'Entry + 5 tasting vouchers', available: 860 },
    ],
  },
];

export const FEATURED_EVENTS = EVENTS.filter((e) => e.isFeatured);
export const TRENDING_EVENTS = EVENTS.filter((e) => e.isTrending);

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '✨' },
  { id: 'music', label: 'Music', icon: '🎵' },
  { id: 'arts', label: 'Arts & Culture', icon: '🎨' },
  { id: 'sports', label: 'Sports & Wellness', icon: '⚽' },
  { id: 'food', label: 'Food & Drinks', icon: '🍽️' },
  { id: 'cinema', label: 'Cinema', icon: '🎬' },
  { id: 'comedy', label: 'Comedy Shows', icon: '😂' },
  { id: 'conferences', label: 'Conferences', icon: '🎤' },
  { id: 'technology', label: 'Technology', icon: '💻' },
  { id: 'family', label: 'Family Events', icon: '👨‍👩‍👧' },
  { id: 'fundraisers', label: 'Fundraisers', icon: '🤝' },
  { id: 'spirituality', label: 'Spirituality', icon: '🙏' },
  { id: 'adventures', label: 'Adventures', icon: '🏔️' },
];

export const CATEGORY_COLORS: Record<string, string> = {
  Music: '#A855F7',
  'Arts & Culture': '#F59E0B',
  'Sports & Wellness': '#10B981',
  'Food & Drinks': '#F97316',
  Cinema: '#3B82F6',
  'Comedy Shows': '#EAB308',
  Conferences: '#6366F1',
  Technology: '#06B6D4',
  'Family Events': '#EC4899',
  Fundraisers: '#EF4444',
  Spirituality: '#8B5CF6',
  Adventures: '#22C55E',
};

export const NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'reminder', title: 'Event Tomorrow!', body: 'Afrobeats Fest Lagos is tomorrow at 7 PM. Get ready!', time: '2h ago', read: false, icon: '🎵' },
  { id: 'n2', type: 'booking', title: 'Booking Confirmed', body: 'Your ticket for NG Tech Summit 2026 has been confirmed.', time: '1d ago', read: false, icon: '✅' },
  { id: 'n3', type: 'promo', title: 'Flash Sale 🔥', body: 'Lagos Food Festival tickets are 20% off for the next 6 hours!', time: '2d ago', read: true, icon: '💥' },
  { id: 'n4', type: 'social', title: 'Chisom saved an event', body: 'Chisom Okafor saved Comedy Night Lagos — you might like it too.', time: '3d ago', read: true, icon: '👤' },
  { id: 'n5', type: 'reminder', title: 'Last Few Tickets', body: 'Only 42 VVIP tables left for Afrobeats Fest Lagos. Book now!', time: '4d ago', read: true, icon: '⚡' },
  { id: 'n6', type: 'promo', title: 'New Events Near You', body: '8 new events added in Lagos this week. Check them out.', time: '5d ago', read: true, icon: '📍' },
];

export const USERS: UserProfile[] = [
  { id: 'u1', name: 'Chisom Okafor', username: 'chisom_events', avatarColor: '#EC4899', avatarInitials: 'CO', city: 'Lagos', bio: 'Event enthusiast 🎉 | Music lover | Always at the next big thing in Lagos', eventsAttended: 34, followers: 1240, following: 312, interests: ['Music', 'Food & Drinks', 'Arts & Culture'] },
  { id: 'u2', name: 'Emeka Nwosu', username: 'emeka.tech', avatarColor: '#3B82F6', avatarInitials: 'EN', city: 'Abuja', bio: 'Tech founder & conference speaker. Building the future of Africa 🚀', eventsAttended: 21, followers: 4800, following: 198, interests: ['Technology', 'Conferences', 'Fundraisers'] },
  { id: 'u3', name: 'Fatima Al-Hassan', username: 'fati_vibes', avatarColor: '#F59E0B', avatarInitials: 'FA', city: 'Kano', bio: 'Cultural curator | Connecting communities through art and food 🎨🍲', eventsAttended: 47, followers: 892, following: 430, interests: ['Arts & Culture', 'Food & Drinks', 'Spirituality'] },
  { id: 'u4', name: 'Tunde Adeyemi', username: 'tunde_sporty', avatarColor: '#22C55E', avatarInitials: 'TA', city: 'Lagos', bio: 'Fitness freak 💪 | Marathon runner | Lagos fitness community organiser', eventsAttended: 58, followers: 2100, following: 520, interests: ['Sports & Wellness', 'Adventures', 'Family Events'] },
  { id: 'u5', name: 'Ngozi Eze', username: 'ngozi.arts', avatarColor: '#8B5CF6', avatarInitials: 'NE', city: 'Port Harcourt', bio: 'Visual artist & gallery curator. Art is life 🖌️', eventsAttended: 29, followers: 3400, following: 280, interests: ['Arts & Culture', 'Cinema', 'Comedy Shows'] },
  { id: 'u6', name: 'Bello Musa', username: 'bello_ent', avatarColor: '#EF4444', avatarInitials: 'BM', city: 'Abuja', bio: 'Entertainment journalist | Music critic | Your go-to for Afrobeats 🎵', eventsAttended: 112, followers: 6700, following: 890, interests: ['Music', 'Comedy Shows', 'Cinema'] },
];

export function formatPrice(amount: number): string {
  return `₦${amount.toLocaleString()}`;
}
