-- Foreign key constraints, applied after every table exists (see note in
-- 0002_tables.sql on why these are separated from CREATE TABLE).

ALTER TABLE admin_action_requests ADD CONSTRAINT admin_action_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE admin_action_requests ADD CONSTRAINT admin_action_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE admin_logs ADD CONSTRAINT admin_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE admin_logs ADD CONSTRAINT admin_logs_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE app_config ADD CONSTRAINT app_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES users (id);
ALTER TABLE checkins ADD CONSTRAINT checkins_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE checkins ADD CONSTRAINT checkins_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE checkins ADD CONSTRAINT checkins_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE;
ALTER TABLE checkins ADD CONSTRAINT checkins_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE conversation_clears ADD CONSTRAINT conversation_clears_other_user_id_fkey FOREIGN KEY (other_user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE conversation_clears ADD CONSTRAINT conversation_clears_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE device_fingerprints ADD CONSTRAINT device_fingerprints_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE device_push_tokens ADD CONSTRAINT device_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE direct_messages ADD CONSTRAINT direct_messages_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL;
ALTER TABLE direct_messages ADD CONSTRAINT direct_messages_reply_to_id_fkey FOREIGN KEY (reply_to_id) REFERENCES direct_messages (id) ON DELETE SET NULL;
ALTER TABLE event_promotions ADD CONSTRAINT event_promotions_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE event_promotions ADD CONSTRAINT event_promotions_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE event_reminder_log ADD CONSTRAINT event_reminder_log_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE CASCADE;
ALTER TABLE events ADD CONSTRAINT events_hidden_by_fkey FOREIGN KEY (hidden_by) REFERENCES users (id);
ALTER TABLE events ADD CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE events ADD CONSTRAINT events_payout_account_id_fkey FOREIGN KEY (payout_account_id) REFERENCES organizer_bank_accounts (id) ON DELETE SET NULL;
ALTER TABLE highlights ADD CONSTRAINT highlights_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE media_assets ADD CONSTRAINT media_assets_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE media_assets ADD CONSTRAINT media_assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE message_reactions ADD CONSTRAINT message_reactions_message_id_fkey FOREIGN KEY (message_id) REFERENCES direct_messages (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE organizer_reviews ADD CONSTRAINT organizer_reviews_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE organizer_reviews ADD CONSTRAINT organizer_reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE organizer_transactions ADD CONSTRAINT organizer_transactions_withdrawal_request_id_fkey FOREIGN KEY (withdrawal_request_id) REFERENCES organizer_withdrawal_requests (id);
ALTER TABLE organizer_withdrawal_requests ADD CONSTRAINT organizer_withdrawal_requests_bank_account_id_fkey FOREIGN KEY (bank_account_id) REFERENCES organizer_bank_accounts (id) ON DELETE SET NULL;
ALTER TABLE organizer_withdrawal_requests ADD CONSTRAINT organizer_withdrawal_requests_organizer_id_public_users_fkey FOREIGN KEY (organizer_id) REFERENCES users (id);
ALTER TABLE pending_purchases ADD CONSTRAINT pending_purchases_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id);
ALTER TABLE pending_purchases ADD CONSTRAINT pending_purchases_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE referrals ADD CONSTRAINT referrals_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE referred_emails ADD CONSTRAINT referred_emails_referrer_id_fkey FOREIGN KEY (referrer_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE reports ADD CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE saved_events ADD CONSTRAINT saved_events_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE saved_events ADD CONSTRAINT saved_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE scan_log ADD CONSTRAINT scan_log_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE scan_log ADD CONSTRAINT scan_log_scanned_by_fkey FOREIGN KEY (scanned_by) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE scan_log ADD CONSTRAINT scan_log_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE SET NULL;
ALTER TABLE tickets ADD CONSTRAINT tickets_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE RESTRICT;
ALTER TABLE tickets ADD CONSTRAINT tickets_refund_initiated_by_fkey FOREIGN KEY (refund_initiated_by) REFERENCES users (id);
ALTER TABLE tickets ADD CONSTRAINT tickets_scanner_id_fkey FOREIGN KEY (scanner_id) REFERENCES users (id) ON DELETE SET NULL;
ALTER TABLE tickets ADD CONSTRAINT tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_privacy_settings ADD CONSTRAINT user_privacy_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE vc_bonuses ADD CONSTRAINT vc_bonuses_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE vc_event_boosts ADD CONSTRAINT vc_event_boosts_event_id_fkey FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE;
ALTER TABLE vc_event_boosts ADD CONSTRAINT vc_event_boosts_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE vc_transactions ADD CONSTRAINT vc_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE vents_wallets ADD CONSTRAINT vents_wallets_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
