-- Indexes, verbatim from the live InsForge database (89 indexes, including
-- pg_trgm GIN indexes for fuzzy search).

CREATE INDEX idx_aar_requested_by ON public.admin_action_requests USING btree (requested_by, requested_at DESC);
CREATE INDEX idx_aar_status_requested_at ON public.admin_action_requests USING btree (status, requested_at DESC);
CREATE INDEX idx_admin_logs_action ON public.admin_logs USING btree (action);
CREATE INDEX idx_admin_logs_admin_id ON public.admin_logs USING btree (admin_id);
CREATE INDEX idx_admin_logs_created_at ON public.admin_logs USING btree (created_at DESC);
CREATE INDEX idx_admin_logs_target_user_id ON public.admin_logs USING btree (target_user_id);
CREATE INDEX idx_app_config_updated_by ON public.app_config USING btree (updated_by);
CREATE INDEX idx_checkins_checked_in_at ON public.checkins USING btree (checked_in_at);
CREATE INDEX idx_checkins_event_checked_at ON public.checkins USING btree (event_id, checked_in_at DESC);
CREATE INDEX idx_checkins_event_id ON public.checkins USING btree (event_id);
CREATE INDEX idx_checkins_scanned_by ON public.checkins USING btree (scanned_by);
CREATE INDEX idx_checkins_ticket_id ON public.checkins USING btree (ticket_id);
CREATE INDEX conversation_requests_recipient_pending_idx ON public.conversation_requests USING btree (recipient_id, status);
CREATE UNIQUE INDEX dp_user_fp ON public.device_fingerprints USING btree (user_id, fingerprint);
CREATE INDEX idx_device_push_tokens_user ON public.device_push_tokens USING btree (user_id);
CREATE INDEX dm_recipient_idx ON public.direct_messages USING btree (recipient_id, created_at DESC);
CREATE INDEX dm_sender_idx ON public.direct_messages USING btree (sender_id, created_at DESC);
CREATE INDEX idx_direct_messages_event_id ON public.direct_messages USING btree (event_id);
CREATE INDEX idx_event_promotions_event_id ON public.event_promotions USING btree (event_id);
CREATE INDEX idx_event_promotions_organizer_id ON public.event_promotions USING btree (organizer_id);
CREATE UNIQUE INDEX idx_event_promotions_payment_ref ON public.event_promotions USING btree (payment_ref);
CREATE INDEX idx_events_category ON public.events USING btree (category);
CREATE INDEX idx_events_category_trgm ON public.events USING gin (category gin_trgm_ops);
CREATE INDEX idx_events_event_date ON public.events USING btree (event_date);
CREATE INDEX idx_events_hidden ON public.events USING btree (hidden_by_admin) WHERE (hidden_by_admin = false);
CREATE INDEX idx_events_hidden_by ON public.events USING btree (hidden_by);
CREATE INDEX idx_events_location_trgm ON public.events USING gin (location gin_trgm_ops);
CREATE INDEX idx_events_organizer_id ON public.events USING btree (organizer_id);
CREATE INDEX idx_events_status ON public.events USING btree (status);
CREATE INDEX idx_events_title_trgm ON public.events USING gin (title gin_trgm_ops);
CREATE INDEX idx_highlights_created_at ON public.highlights USING btree (created_at DESC);
CREATE INDEX idx_highlights_group_id ON public.highlights USING btree (group_id);
CREATE INDEX idx_highlights_user_group ON public.highlights USING btree (user_id, group_id, sort_order);
CREATE INDEX idx_highlights_user_id ON public.highlights USING btree (user_id);
CREATE INDEX idx_media_assets_event ON public.media_assets USING btree (event_id);
CREATE INDEX idx_media_assets_uploaded ON public.media_assets USING btree (uploaded_at DESC);
CREATE INDEX idx_media_assets_user ON public.media_assets USING btree (user_id);
CREATE INDEX message_reactions_message_idx ON public.message_reactions USING btree (message_id);
CREATE INDEX idx_notifications_push_pending ON public.notifications USING btree (created_at) WHERE (push_sent = false);
CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);
CREATE UNIQUE INDEX uniq_org_bank_account ON public.organizer_bank_accounts USING btree (organizer_id, account_number);
CREATE UNIQUE INDEX uniq_org_default_bank ON public.organizer_bank_accounts USING btree (organizer_id) WHERE (is_default AND is_active);
CREATE INDEX idx_organizer_requests_reviewed_by ON public.organizer_requests USING btree (reviewed_by);
CREATE INDEX idx_organizer_requests_user_id ON public.organizer_requests USING btree (user_id);
CREATE INDEX organizer_reviews_organizer_idx ON public.organizer_reviews USING btree (organizer_id);
CREATE INDEX organizer_reviews_reviewer_idx ON public.organizer_reviews USING btree (reviewer_id);
CREATE INDEX idx_org_txns_organizer ON public.organizer_transactions USING btree (organizer_id, created_at DESC);
CREATE UNIQUE INDEX organizer_verification_requests_one_pending_per_user ON public.organizer_verification_requests USING btree (user_id) WHERE (status = 'pending'::text);
CREATE INDEX idx_org_withdraw_organizer ON public.organizer_withdrawal_requests USING btree (organizer_id, created_at DESC);
CREATE INDEX idx_org_withdraw_status ON public.organizer_withdrawal_requests USING btree (status);
CREATE INDEX idx_organizer_withdrawal_requests_bank_account_id ON public.organizer_withdrawal_requests USING btree (bank_account_id);
CREATE INDEX idx_pending_purchases_dedup ON public.pending_purchases USING btree (user_id, event_id, ticket_type, attendees_hash, status, created_at DESC);
CREATE UNIQUE INDEX referrals_referrer_invitee_idx ON public.referrals USING btree (referrer_id, invitee_email);
CREATE INDEX idx_referred_emails_referrer_id ON public.referred_emails USING btree (referrer_id);
CREATE INDEX reports_reporter_idx ON public.reports USING btree (reporter_id);
CREATE INDEX reports_status_idx ON public.reports USING btree (status);
CREATE INDEX reports_target_idx ON public.reports USING btree (target_type, target_id);
CREATE INDEX idx_saved_events_event_id ON public.saved_events USING btree (event_id);
CREATE INDEX idx_saved_events_user_id ON public.saved_events USING btree (user_id);
CREATE INDEX idx_scan_log_event_created ON public.scan_log USING btree (event_id, created_at DESC);
CREATE INDEX idx_scan_log_event_result ON public.scan_log USING btree (event_id, result);
CREATE INDEX idx_tickets_event_id ON public.tickets USING btree (event_id);
CREATE INDEX idx_tickets_payment_ref ON public.tickets USING btree (payment_ref);
CREATE UNIQUE INDEX idx_tickets_refund_id ON public.tickets USING btree (refund_id) WHERE (refund_id IS NOT NULL);
CREATE INDEX idx_tickets_user_id ON public.tickets USING btree (user_id);
CREATE INDEX idx_users_full_name_trgm ON public.users USING gin (full_name gin_trgm_ops);
CREATE INDEX idx_users_username_trgm ON public.users USING gin (username gin_trgm_ops);
CREATE INDEX idx_vc_event_boosts_user_id ON public.vc_event_boosts USING btree (user_id);
CREATE UNIQUE INDEX vc_transactions_referral_dedup_idx ON public.vc_transactions USING btree (user_id, reference_id) WHERE (type = 'referral'::text);
CREATE INDEX vc_transactions_status_expires_idx ON public.vc_transactions USING btree (user_id, status, expires_at);
CREATE INDEX vc_transactions_user_id_idx ON public.vc_transactions USING btree (user_id);
